import "./globals.css";
import { cookies } from 'next/headers';
import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import type { Metadata } from "next";
import { Cairo } from 'next/font/google';
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { Toaster } from 'react-hot-toast'

export const metadata: Metadata = {
  title: "Beit Meryam",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png", 
  }
};

const cairo = Cairo({
  subsets: ['arabic', 'latin'],
  weight: ['400', '700'],
  variable: '--font-cairo',
});

export default async function LocaleLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  // قراءة الكوكيز
  const cookieStore = cookies();
  const theme = (await cookieStore).get('theme'); // الكوكيز اسمها 'theme'

  const isDark = theme?.value === 'dark';

  return (
    <html
      lang={locale}
      dir={locale === 'ar' ? 'rtl' : 'ltr'}
      className={`${cairo.className} ${isDark ? 'dark' : ''}`}
    >
      <body className=" text-black dark:text-white bg-[url(/bg.png)] bg-fixed bg-cover bg-center dark:bg-none dark:bg-black">
        <NextIntlClientProvider>
               <Toaster position="top-right" reverseOrder={false} />
          <Header/>
          {children}
          <Footer/>
          </NextIntlClientProvider>
      </body>
    </html>
  );
}
